### ISSUE TITLE
Project Page: Display Related Partners

### ISSUE THREAD

**Issue by lsweltz** [InterActionNGO/ngoaidmap#10] opened 2016-08-26 20:09 UTC
On the individual project page:

Display all related partners in the sidebar.
- All organizations with an international organization distinction will display within the international partners section of the projects page.
- All organizations with a local organization distinction will display within the local partners section of the projects page.

**Comment by mzlock** [comment] 2016-10-07 22:37
Duplicate of #32 ?

**Closed** 2016-10-14 17:06 UTC
Labels: question
